services:

  autogentoo-builder:
    image: colingilbert/stage3:amd64-musl-hardened
    volumes:
      - binpkgs:/var/cache/binpkgs
      - distfiles:/var/cache/distfiles
      - ebuilds:/var/db/repos/gentoo
      - ./build/config/autogentoo-builder/make.conf:/etc/portage/make.conf:ro
      - ./build/config/autogentoo-builder/package.mask:/etc/portage/package.mask:ro
      - ./build/config/autogentoo-builder/package.unmask:/etc/portage/package.unmask:ro
      - ./build/config/autogentoo-builder/package.accept_keywords:/etc/portage/package.accept_keywords:ro
      - ./build/config/autogentoo-builder/package.license:/etc/portage/package.license:ro
      - ./build/config/autogentoo-builder/package.use:/etc/portage/package.use:ro
      - ./build/config/autogentoo-builder/repos.conf:/etc/portage/repos.conf:ro
      - ./build/config/autogentoo-builder/sets:/etc/portage/sets:ro
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys:ro

  autogentoo-rsyncd:
    image: colingilbert/rsync
    command: rsync --daemon --no-detach
    ports:
      - "873:873"
    volumes:
      - ebuilds:/mnt:ro
      - ./config/rsyncd/rsyncd.conf:/etc/rsyncd.conf:ro

        #autogentoo-package-host:
        # image: caddy/caddy:alpine
        # volumes:
        # - binpkgs:/data:ro
        # ports:
        # - "80:80"

networks:
  frontend:
    driver: host
  backend:
    driver: overlay

volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
  configs:
    driver: local
