services:

  infrastructure/builder:
    image: autogentoo-builder
    networks:
      - backend
    volumes:
      - binpkgs:/var/cache/binpkgs
      - distfiles:/var/cache/distfiles
      - ebuilds:/var/db/repos/gentoo
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys:ro

  autogentoo-rsync:
    image: colingilbert/rsync
    command: rsync --daemon --no-detach
    networks:
      - backend
    ports:
      - "873:873"
    volumes:
      - ebuilds:/mnt/portage:ro
      - distfiles:/mnt/distfiles:ro
      - ebuilds:/var/db/repos/gentoo:ro
      - ./config/autogentoo/portage/rsyncd.conf:/etc/rsyncd.conf:ro

    
networks:
  frontend:
    driver: host
  backend:
    driver: overlay

volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
  configs:
    driver: local
