services:

  autogentoo-builder:
    image: colingilbert/stage3:amd64-musl-hardened
    volumes:
      - binpkgs:/var/cache/binpkgs
      - distfiles:/var/cache/distfiles
      - ebuilds:/var/db/repos/gentoo
      - ./build/config:/etc/portage:ro
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys:ro

  autogentoo-rsyncd:
    image: colingilbert/rsync
    command: rsync --daemon --no-detach
    ports:
      - "873:873"
    volumes:
      - ebuilds:/data:ro
      - ./config/rsyncd/rsyncd.conf:/etc/rsyncd.conf:ro

  autogento-package-host:
    image: caddy/caddy:alpine
    volumes:
      - binpkgs:/data:ro
    ports:
      - "8000:80"

networks:
  frontend:
    driver: host
  backend:
    driver: overlay

volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
  configs:
    driver: local
