services:
  bootstrap:
    image: gentoo/stage3:musl-hardened
    volumes:
      - binpkgs:/var/cache/binpkgs
      - distfiles:/var/cache/distfiles
      - ebuilds:/var/db/repos/gentoo
      - ./config/make.conf:/etc/portage/make.conf:ro
      - ./config/package.use:/etc/portage/package.use:ro
      - ./config/package.accept_keywords:/etc/portage/package.accept_keywords:ro
      - ./config/package.unmask:/etc/portage/package.unmask:ro
      - ./config/package.mask:/etc/portage/package.mask:ro
      - ./config/package.license:/etc/portage/package.license:ro
      - ./config/sets:/etc/portage/sets:ro
      - /dev:/dev
      - /proc:/proc
      - /sys:/sys



volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
