# Do not make changes to this file, as they will be overriden upon the next build.
services:
  gentoomuch-builder:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-stage3
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs
    - distfiles:/var/cache/distfiles
    - ebuilds:/var/db/repos/gentoo
    - stages:/mnt/stages:ro
    - kernels:/mnt/kernels
    - ./work/squashed/mountpoint:/mnt/squashed-portage:ro
  gentoomuch-packer:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-stage3
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs:ro
    - distfiles:/var/cache/distfiles:ro
    - ebuilds:/var/db/repos/gentoo:ro
    - stages:/mnt/stages
    - kernels:/mnt/kernels:ro
    - ./work/squashed/mountpoint:/mnt/squashed-portage:ro
  gentoomuch-updater:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-stage3
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs
    - distfiles:/var/cache/distfiles
    - ebuilds:/var/db/repos/gentoo
    - stages:/mnt/stages:ro
    - kernels:/mnt/kernels
    - ./work/squashed/blob:/mnt/squashed-portage
networks:
#  frontend:
#    driver: overlay
  backend:
    driver: overlay

volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
  stages:
    driver: local
  kernels:
    driver: local
