# Do not make changes to this file, as they will be overriden upon the next build.
services:
  gentoomuch-builder:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-current
    cap_add:
    - CAP_SYS_ADMIN
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs
    - distfiles:/var/cache/distfiles
    - ebuilds:/var/db/repos/gentoo
    - kernels:/mnt/kernels
    - ./work/squashed/mountpoint:/mnt/squashed-portage:ro
    - ./work/stages:/mnt/stages:ro
    - ./work/portage/package.use:/etc/portage/package.use:ro
    - ./work/portage/package.license:/etc/portage/package.license:ro
    - ./work/portage/make.conf:/etc/portage/make.conf:ro
    - ./work/portage/sets/gentoomuch/sway-desktop:/etc/portage/sets/gentoomuch/sway-desktop:ro
    - ./work/portage/sets/gentoomuch/builder:/etc/portage/sets/gentoomuch/builder:ro
    - ./work/portage/repos.conf/gentoo.conf:/etc/portage/repos.conf/gentoo.conf:ro
  gentoomuch-packer:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-current
    cap_add:
    - CAP_SYS_ADMIN
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs:ro
    - distfiles:/var/cache/distfiles:ro
    - ebuilds:/var/db/repos/gentoo:ro
    - kernels:/mnt/kernels:ro
    - ./work/squashed/mountpoint:/mnt/squashed-portage:ro
    - ./work/stages:/mnt/stages
    - ./work/portage/package.use:/etc/portage/package.use:ro
    - ./work/portage/package.license:/etc/portage/package.license:ro
    - ./work/portage/make.conf:/etc/portage/make.conf:ro
    - ./work/portage/sets/gentoomuch/sway-desktop:/etc/portage/sets/gentoomuch/sway-desktop:ro
    - ./work/portage/sets/gentoomuch/builder:/etc/portage/sets/gentoomuch/builder:ro
    - ./work/portage/repos.conf/gentoo.conf:/etc/portage/repos.conf/gentoo.conf:ro
  gentoomuch-updater:
    # The following line is a cool trick that fools the docker program into using a locally-tagged image as if it came from a proper repository.
    image: localhost:5000/gentoomuch-amd64-current
    cap_add:
    - CAP_SYS_ADMIN
    networks:
    - backend
    volumes:
    - /dev:/dev
    - /proc:/proc
    - /sys:/sys:ro
    - binpkgs:/var/cache/binpkgs
    - distfiles:/var/cache/distfiles
    - ebuilds:/var/db/repos/gentoo
    - kernels:/mnt/kernels
    - ./work/squashed/blob:/mnt/squashed-portage
    - ./work/stages:/mnt/stages:ro
    - ./work/portage/package.use:/etc/portage/package.use:ro
    - ./work/portage/package.license:/etc/portage/package.license:ro
    - ./work/portage/make.conf:/etc/portage/make.conf:ro
    - ./work/portage/sets/gentoomuch/sway-desktop:/etc/portage/sets/gentoomuch/sway-desktop:ro
    - ./work/portage/sets/gentoomuch/builder:/etc/portage/sets/gentoomuch/builder:ro
    - ./work/portage/repos.conf/gentoo.conf:/etc/portage/repos.conf/gentoo.conf:ro
networks:
#  frontend:
#    driver: overlay
  backend:
    driver: overlay

volumes:
  distfiles:
    driver: local
  ebuilds:
    driver: local
  binpkgs:
    driver: local
  kernels:
    driver: local
#  stage-packing:
#    driver: local
