#!/usr/bin/env python3

import os, sys, re
from typing import Tuple
from include.gentoomuch_common import arch_config_path, config_path, output_path, usage_str
from include.freshroot import freshroot
from include.sync import sync, has_sync_happened, set_sync_happened
from include.swap_stage import swap_stage
from include.composefile import create_composefile
from include.tag_parser import tag_parser
from include.get_active_stage import get_active_stage
from include.list_stages import list_stages
from include.list_profiles import list_profiles
from include.set_desired_stage import set_desired_stage
from include.set_desired_profile import set_desired_profile
from include.get_desired_stage import get_desired_stage
from include.get_desired_profile import get_desired_profile
from include.run_build import run_build
from include.get_docker_tag import get_docker_tag
from include.save_tarball import save_tarball
from include.load_tarball import load_tarball
from include.patches import prep_patch, try_patch, save_patch
from include.ui_patch_prep_handler import ui_patch_prep_handler, prep_str
from include.downloader import downloader
from include.get_profiles import get_profiles
from include.remove_old_docker_images import remove_old_docker_images

# Our commandline keywords
ls_str          = 'ls'
set_str         = 'set'
sync_str        = 'sync'
patch_str       = 'patch'
pipeline_str    = 'pipeline'
freshroot_str   = 'freshroot'
bootstrap_str   = 'bootstrap'
profile_str     = 'profile'
stage_str       = 'stage'
patch_str       = 'patch'
all_str         = 'all'
prep_str        = 'prep'
try_str         = 'try'
save_str        = 'save'
apply_str       = 'apply'


# First word after the "gentoomuch" command.
primary_commands = (profile_str, stage_str, sync_str, pipeline_str, freshroot_str, bootstrap_str, patch_str )
# Commands you can use ls and set to visualize and manipulate.
#ls_and_set_usedwiths = (profile_str, stage_str)
# 
#verbs = (ls_str, set_str)

# Here we define CLI help functions for when the user needs it.

# Print usage_str messages.
def print_usage_stage_ls():
    print(usage_str + stage_str + ' ' + ls_str)

def print_usage_stage_set():
    print(usage_str + stage_str + ' ' + set_str + ' <name>')

def print_usage_profile_ls():
    print(usage_str + profile_str + ' ' + ls_str)

def print_usage_profile_set():
    print(usage_str + profile_str + ' ' + set_str + ' <name>')

def print_usage_stage():
    print_usage_stage_ls()
    print_usage_stage_set()

def print_usage_profile():
    print_usage_profile_ls()
    print_usage_profile_set()

def print_usage_bootstrap():
    print(usage_str + bootstrap_str + ' <profile> <tarball>')

def print_usage_patch():
    patch_usage = usage_str + patch_str + ' '
    print(patch_usage + prep_str + '  <name> <package> <version-str>')
    print(patch_usage + try_str + ' <name>')
    print(patch_usage + save_str + ' <name>')
    print(patch_usage + apply_str + ' <name>')

def print_no_profile():
    print("You need to set a base profile before continuing.")

def print_usage():
    print(usage_str + freshroot_str)
    print(usage_str + pipeline_str)
    print(usage_str + sync_str)
    print_usage_bootstrap()
    print_usage_profile()
    print_usage_stage()

# We do this every time!
arch = open(arch_config_path).read().strip()


#get_profiles()

# Now, we get properly started.
########################
# Get the first command.
########################
prime_cmd = ''
if len(sys.argv) > 1:
    if sys.argv[1] in primary_commands:
        prime_cmd = sys.argv[1]
    else:
        print_usage()
        exit()
##############################################
# Stage definitions-related commands (ls/set).
##############################################
if prime_cmd == stage_str:
    if sys.argv[2] == ls_str and len(sys.argv) == 3: # Listing stages
        list_stages()
        exit()
    elif sys.argv[2] == set_str and len(sys.argv) == 4: # Setting stage
        if not sys.argv[3].isnumeric():
            set_desired_stage(sys.argv[3])
        else:
            print("You need to set a stage by name, as numbers will change over time.")
        exit()
    else: # Error message for stages
        print_usage_stage()
        exit()
###################################
# Profile-related command (ls/set).
###################################
elif prime_cmd == profile_str:
    if sys.argv[2] == ls_str and len(sys.argv) == 3: # Listing profiles
        list_profiles(arch)
        exit()
    elif sys.argv[2] == set_str and len(sys.argv) == 4: # Setting profile
        if not sys.argv[3].isnumeric():
            set_desired_profile(arch, sys.argv[3])
        else:
            print("You need to set a profile by name.")
        exit()
    else: # Error message for profile
        print_usage_profile() 
        exit()
#############################################
# Bootstrap a stage from a tarball.
#############################################
elif prime_cmd == bootstrap_str:
    if not len(sys.argv) == 4:
        print_usage_bootstrap()
        exit()
    profile = sys.argv[2]
    code = create_composefile(output_path)
    if code:
      pass
    path = os.path.join(os.getcwd(), sys.argv[3])
    code = load_tarball(arch, profile, path)
    if not code:
        exit("Failed to load tarball")
    if not has_sync_happened():
        print("Syncing for first time!")
        code = sync()
        if code != 0:
            exit("Could not sync")
        set_sync_happened()
        save_tarball(arch, profile, "gentoomuch/builder", True)
    else:
        save_tarball(arch, profile, "gentoomuch/builder", True)
    remove_old_docker_images()
    exit()
##################
# Handle patching.
##################
elif prime_cmd == patch_str:
    error_str = usage_str
    if len(sys.argv) == 2:
        print_usage_patch()
    if len(sys.argv) > 2 and sys.argv[2] == prep_str:
        ui_patch_prep_handler(3).handle()
    elif len(sys.argv) > 2 and sys.argv[2] == try_str:
        if len(sys.argv) > 3:
            patch_name = sys.argv[3]
            #print(patch_name)
            valid, profile = get_desired_profile()
            if valid:
                try_patch(profile, patch_name)
            else:
                exit("Need to have a profile set.")
        else:
            exit("You need to provide a patch name to try.")
    # We save a patch to our config/patches directory
    elif len(sys.argv) > 2 and sys.argv[2] == save_str:
        if len(sys.argv) > 3:
            patch_name = sys.argv[3]
            save_patch(patch_name)
        else:
            exit("Which patch do you wish to save?")
    elif len(sys.argv) > 2 and sys.argv[2] == apply_str:
        if len(sys.argv) > 3:
            patch_name = sys.argv[3]
            profiles = get_profiles()
            for profile in profiles: 
                results = save_tarball(arch, profile, "gentoomuch/builder", False, patch_name, False)
                if results:
                    pass
                #TODO: Add the rest in the pipeline
        else:
            exit("Which patch to apply to your pipelines?")
    exit()
##################################
# Deal with the freshroot command. 
##################################
elif prime_cmd == freshroot_str: 
    #swap_stage(arch, 'default', 'gentoomuch/builder')
    freshroot()
#######################
# Run pipelined builds.
#######################
elif prime_cmd == pipeline_str:
    print('Running pipeline')
    # Get stage defines from buildlist and build them.
    # TODO: Implement
####################
# Sync Portage tree. 
####################
elif prime_cmd == sync_str:
    if has_sync_happened():
        valid, profile = get_desired_profile()
        if valid:
            swap_stage(arch, profile, 'gentoomuch/builder', False)
            sync()
        else:
            exit("Need to select a working profile prior to sync.")
    else:
        exit("Need to bootstrap a stage3 prior to first sync")
else:
    print_usage()
